#!/bin/bash

## Push repo
push() {
	(git -C "$1" push origin master || git -C "$1" push origin main) 2> /dev/null > /dev/null
}

remove_origin() {
	git -C "$1" remote remove origin 2> /dev/null > /dev/null;
}

## Checks the number of argument is correct
if [ "$#" -ne "4" ];
then
	echo 'USAGE: blih2github $GITHUB_UNAME $GITHUB_ORGA $GITHUB_ACCESSTOKEN $DIR'
	exit 1
fi

GITHUB_UNAME="$1"
GITHUB_ORGA="$2"
GITHUB_ACCESSTOKEN="$3"
DIR="$4"

if [[ ! -d "$DIR" ]];
then
	echo "'$DIR': Is not an accessible directory"
	exit 1
fi

for blih_dir in "$DIR"/**;
do
	# If it is not a git repository, continue
	if [[ ! -d "$blih_dir" || ! -d "$blih_dir/.git" ]];
	then
		continue
	fi
	repo_name=$(basename "$blih_dir")


	echo "'$repo_name' is a Git Repository"
	## Create repo in Github
	echo "Creating '$repo_name' repository in '$GITHUB_ORGA'..."
	http_code=$(curl -i -u "$GITHUB_UNAME:$GITHUB_ACCESSTOKEN" -X POST \
		-H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/$GITHUB_ORGA/repos" \
		-d "{\"name\":\"$repo_name\", \"visibility\": \"private\"}" --write-out %{http_code} --silent --output curl_output.log)
	if [[ "$http_code" != "201" ]];
	then
		echo "Oops.. Something went wrong with Github while creating the repository... Here is what happened:"
		cat curl_output.log ; rm curl_output.log
		exit 1
	fi
	rm -f curl_output.log
	# Waiting for the repository to be available
	sleep 6
	## adding remote to local repo
	remove_origin "$blih_dir"
	## Push to remote via SSH
	git -C "$blih_dir" remote add origin "git@github.com:$GITHUB_ORGA/$repo_name.git"
	## If Push failed
	if ! push "$blih_dir" ;
	then
		## Push via http
		git -C "$blih_dir" remote set-url origin "https://$GITHUB_ORGA:$GITHUB_ACCESSTOKEN@github.com/$GITHUB_ORGA/$repo_name"
		if ! push "$blih_dir";
		then
			echo "Oops.. Something went wrong while pushing to remote"
			exit 1
		fi
	fi
	echo "Congrats! '$repo_name' is now available on github! check it out here: https://github.com/$GITHUB_ORGA/$repo_name."
done

exit 0