#!/bin/bash

## Checks the number of argument is correct
if [ "$#" -ne "4" ];
then
	echo 'USAGE: blih2github $GITHUB_UNAME $GITHUB_ORGA $GITHUB_ACCESSTOKEN $DIR'
	exit 1
fi

GITHUB_UNAME="$1"
GITHUB_ORGA="$2"
GITHUB_ACCESSTOKEN="$3"
DIR="$4"

if [[ ! -d "$DIR" ]];
then
	echo "'$DIR': Is not an accessible directory"
	exit 1
fi

for blih_dir in "$DIR"/**;
do
	# If it is not a git repository, continue
	if [[ ! -d "$blih_dir" || ! -d "$blih_dir/.git" ]];
	then
		continue
	fi
	repo_name=$(basename "$blih_dir")
	echo "'$repo_name' is a Git Repository"
	## Create repo in Github
	echo "Creating '$repo_name' repository in '$GITHUB_ORGA'..."
	curl -i -u "$GITHUB_UNAME:$GITHUB_ACCESSTOKEN" -X POST \
		-H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/$GITHUB_ORGA/repos" \
		-d "{\"name\":\"$repo_name\", \"visibility\": \"private\"}"  #2> /dev/null > /dev/null
	if [ "$?" -ne "0" ];
	then
		echo "Oops.. Something went wrong with Github while creating the repository, moving on to the next one..."
		continue
	fi
	## adding remote to local repo
	git -C "$blih_dir" remote remove origin #2> /dev/null > /dev/null;
	## Push to remote
	(git -C "$blih_dir" remote add origin git@github.com:"$GITHUB_ORGA"/"$repo_name".git || \
	git -C "$blih_dir" remote add origin https://github.com/"$GITHUB_ORGA"/"$repo_name".git) &&
	(git -C "$blih_dir" push origin master || git -C "$blih_dir" push origin main) #2> /dev/null > /dev/null
	if [ "$?" -ne "0" ];
	then
		echo "Oops.. Something went wrong while pushing to remote, moving on to the next one..."
		continue
	fi
	echo "Congrats! '$repo_name' is now available on github! check it out here: https://github.com/$GITHUB_ORGA/$repo_name."
done

exit 0