name: Functionnal Testing
on: [push, workflow_dispatch]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            os: Linux
          - runs-on: windows-latest
            os: Windows
          - runs-on: macOS-latest
            os: macOs
    name: "Run test on ${{ matrix.os }}"
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v1
      - name: Create testing environment
        run: |
        mkdir tests && cd tests
        mkdir testa testb testc
        touch testd testa/a testb/b testc/c
        git -C testa init
        git -C testc init
        git -C testa add .
        git -C testc add .
        git -C testa commit -m "a"
        git -C testc commit -m "c"
      - name: Check testing environment
        run: ls -lR ; tree
