name: Functionnal Testing
on: [push, workflow_dispatch]

jobs:
  tests:
    strategy:
      fail-fast: false
      env:
        orga: EpiBlih
      matrix:
        include:
          - runs-on: ubuntu-latest
            os: Linux
          - runs-on: windows-latest
            os: Windows
          - runs-on: macOS-latest
            os: macOs
    name: "Run test on ${{ matrix.os }}"
    runs-on: ${{ matrix.runs-on }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v1
      - name: Create testing environment
        run: |
          git config --global user.email "${GITHUB_ACTOR}@github.com";
          git config --global user.name "${GITHUB_ACTOR}";
          mkdir tests && cd tests
          mkdir testa testb testc
          touch testd testa/a testb/b testc/c
          git -C testa init
          git -C testc init
          git -C testa add .
          git -C testc add .
          git -C testa commit -m "a"
          git -C testc commit -m "c"
      - name: Run blih2github
        run: ./blih2github  "${GITHUB_ACTOR}" "${{env.orga}}" "${GITHUB_TOKEN}" tests
      - name: Check repository exists
        run: |
          git pull git@github.com:${{env.orga}}/testb.git; ## the repo should not exist
          git pull git@github.com:${{env.orga}}/testa.git
          git pull git@github.com:${{env.orga}}/testc.git
          test -f testa/a
          test ! -e testb
          test -f testc/c
      - name: Cleanup
        run: |
         	curl -i -u "${GITHUB_ACTOR}:${GITHUB_TOKEN}" -X POST -H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/${{env.orga}}/repos" -d "{\"name\":\"testa\"}"
          curl -i -u "${GITHUB_ACTOR}:${GITHUB_TOKEN}" -X POST -H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/${{env.orga}}/repos" -d "{\"name\":\"testc\"}"
