name: Functionnal Testing
on: [push, workflow_dispatch]

jobs:
  tests:
    env:
      orga: EpiBlih
      dir1: test1${{ matrix.runs-on }}
      dir3: test3${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            os: Linux
          - runs-on: windows-latest
            os: Windows
          - runs-on: macOS-latest
            os: macOs
    name: "Run test on ${{ matrix.os }}"
    runs-on: ${{ matrix.runs-on }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v1
      - name: Create testing environment
        run: |
          git config --global user.email "${GITHUB_ACTOR}@github.com";
          git config --global user.name "${GITHUB_ACTOR}";
          mkdir tests && cd tests
          mkdir ${{env.dir1}} testb ${{env.dir3}}
          touch testd ${{env.dir1}}/a testb/b ${{env.dir3}}/c
          git -C ${{env.dir1}} init
          git -C ${{env.dir3}} init
          git -C ${{env.dir1}} add .
          git -C ${{env.dir3}} add .
          git -C ${{env.dir1}} commit -m "a"
          git -C ${{env.dir3}} commit -m "c"
          git config --global --list
      - name: Run blih2github
        run: ./blih2github  "${GITHUB_ACTOR}" "${{env.orga}}" "${{ secrets.atoken }}" tests
      - name: Check repository exists
        run: |
          git pull git@github.com:${{env.orga}}/testb.git; ## the repo should not exist
          git pull git@github.com:${{env.orga}}/${{env.dir1}}.git
          git pull git@github.com:${{env.orga}}/${{env.dir3}}.git
          test -f ${{env.dir1}}/a
          test ! -e testb
          test -f ${{env.dir3}}/c
      - name: Cleanup
        if: ${{ always() }}
        run: |
          curl -i -u "${GITHUB_ACTOR}:${{ secrets.atoken }}" -X POST -H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/${{env.orga}}/repos" -d "{\"name\":\"${{env.dir1}}\"}"
          curl -i -u "${GITHUB_ACTOR}:${{ secrets.atoken }}" -X POST -H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/${{env.orga}}/repos" -d "{\"name\":\"${{env.dir3}}\"}"
